In [1]:
import numpy as np

In [38]:
a=np.arange(24).reshape(4,6)
b=np.ones(12).reshape(4,3)
print('a:\n shape',str(a.shape)+'\n',a)
print('b:\n shape',str(b.shape)+'\n',b)

a:
 shape (4, 6)
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
b:
 shape (4, 3)
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
c=np.concatenate((a,b),axis=1)
c

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  1.,  1.,  1.],
       [ 6.,  7.,  8.,  9., 10., 11.,  1.,  1.,  1.],
       [12., 13., 14., 15., 16., 17.,  1.,  1.,  1.],
       [18., 19., 20., 21., 22., 23.,  1.,  1.,  1.]])

In [45]:
for i in range(10,8,-1):
    print(i)

10
9
